""" THIS FILE IS GENERATED BY A CODE GENERATOR - THIS IS CREATED AS A REFERENCE FOR LEARNING PURPOSES! """



"""
Image preprocessing for handwritten digit recognition.

Turns a photo of a handwritten digit into the exact format an MNIST-trained
model expects: a 28x28 image, white ink on a black background, with the digit
sized and centred the same way MNIST's own digits are.

Each step is its own function so you can run them one at a time and look at
what changed. Read them in the order they appear in `preprocess()`.

Run it:
    python preprocessing.py my_digit.png
"""

import sys

import cv2
import numpy as np


def to_grayscale(image):
    """Colour -> single channel. The model only cares about brightness."""
    if image.ndim == 2:
        return image
    return cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)


def denoise(gray, ksize=3):
    """Smooth out camera noise and paper texture.

    Median blur replaces each pixel with the median of its neighbours. It kills
    isolated specks without blurring the edges of strokes, which a Gaussian
    blur would. ksize must be odd; bigger = smoother but loses thin strokes.
    """
    return cv2.medianBlur(gray, ksize)


def make_ink_dark(gray):
    """Make sure the ink is dark and the background is light.

    Why: the thresholding step below assumes dark ink. If you feed it a
    whiteboard photo or an already-inverted image, it produces a hollow outline
    of the digit instead of the digit.

    How: the border of an image is almost always background. Otsu picks a
    brightness value that splits the image into "dark" and "light". If the
    border falls on the dark side, the background is dark, so we flip it.
    """
    threshold, _ = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    border = np.concatenate([
        gray[:3, :].ravel(), gray[-3:, :].ravel(),
        gray[:, :3].ravel(), gray[:, -3:].ravel(),
    ])
    if border.mean() < threshold:
        return cv2.bitwise_not(gray)
    return gray


def binarize(gray, block=35, c=11):
    """Grayscale -> pure black and white, with the ink turned white.

    Adaptive thresholding compares each pixel to the average of the block x block
    pixels around it, rather than to one value for the whole image. That is what
    lets it cope with a photo that is bright on one side and shadowed on the other.

    `block` must be odd and should be noticeably larger than your stroke width,
    or thick strokes come out hollow. `c` is subtracted from the local average:
    raise it if the background comes out speckled.

    THRESH_BINARY_INV flips the result so the ink is white (255) and the paper
    is black (0) - the MNIST convention.
    """
    return cv2.adaptiveThreshold(
        gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, block, c
    )


def clean(binary, ksize=2):
    """Remove leftover specks of background noise.

    Opening = erode then dilate. Small blobs disappear entirely; the digit,
    being much bigger, survives with its shape roughly intact.
    """
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))
    return cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel)


def deskew(binary):
    """Straighten a slanted digit.

    Image moments describe how the white pixels are spread out. mu11 measures
    how much the spread tilts diagonally and mu02 how tall it is; their ratio is
    the slant. We then shear the image by that amount to cancel it out.
    """
    m = cv2.moments(binary)
    if abs(m["mu02"]) < 1e-2:
        return binary
    slant = m["mu11"] / m["mu02"]
    height, width = binary.shape
    shear = np.float32([[1, slant, -0.5 * height * slant], [0, 1, 0]])
    return cv2.warpAffine(binary, shear, (width, height), flags=cv2.WARP_INVERSE_MAP)


def center_by_mass(image):
    """Slide the digit so its centre of mass sits at the centre of the image.

    MNIST centres digits by centre of mass, not by bounding box. A "7" has most
    of its ink up top, so the two are not the same, and matching MNIST here is
    worth real accuracy.
    """
    m = cv2.moments(image)
    if m["m00"] == 0:
        return image
    cx = m["m10"] / m["m00"]
    cy = m["m01"] / m["m00"]
    rows, cols = image.shape
    shift = np.float32([[1, 0, round(cols / 2 - cx)], [0, 1, round(rows / 2 - cy)]])
    return cv2.warpAffine(image, shift, (cols, rows))


def fit_to_mnist(binary, box=20, canvas=28):
    """Crop to the digit, scale it into a 20x20 box, pad out to 28x28, centre it.

    This is exactly how the MNIST images were built, and copying it is the main
    reason a model trained on MNIST will work on your own photos.

    The longest side goes to 20 pixels and the other side scales with it, so the
    digit is never stretched. INTER_AREA averages pixels as it shrinks, which
    produces the soft grey edges MNIST digits have rather than hard black/white.
    """
    coords = cv2.findNonZero(binary)
    if coords is None:                       # nothing found - blank image
        return np.zeros((canvas, canvas), np.uint8)

    x, y, w, h = cv2.boundingRect(coords)
    digit = binary[y:y + h, x:x + w]

    if h >= w:
        new_h, new_w = box, max(1, round(w * box / h))
    else:
        new_h, new_w = max(1, round(h * box / w)), box
    digit = cv2.resize(digit, (new_w, new_h), interpolation=cv2.INTER_AREA)

    result = np.zeros((canvas, canvas), np.uint8)
    top = (canvas - new_h) // 2
    left = (canvas - new_w) // 2
    result[top:top + new_h, left:left + new_w] = digit

    return center_by_mass(result)


def preprocess(image):
    """Full pipeline: any image of one digit -> 28x28 uint8, ready for a model."""
    gray = to_grayscale(image)
    gray = denoise(gray)
    gray = make_ink_dark(gray)
    binary = binarize(gray)
    binary = clean(binary)
    binary = deskew(binary)
    return fit_to_mnist(binary)


def to_model_input(image28):
    """28x28 uint8 -> float32 in [0, 1], shaped (1, 28, 28).

    Whatever you do here you must also do to your training images, or the model
    sees a different kind of input at test time than it learned from.
    """
    return (image28.astype(np.float32) / 255.0)[np.newaxis, ...]


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("usage: python preprocessing.py <image>")
        raise SystemExit(1)

    image = cv2.imread(sys.argv[1], cv2.IMREAD_COLOR)
    if image is None:
        print(f"could not read {sys.argv[1]}")
        raise SystemExit(1)

    # Save every stage so you can open them and see what each step did.
    gray = to_grayscale(image)
    denoised = denoise(gray)
    ink_dark = make_ink_dark(denoised)
    binary = binarize(ink_dark)
    cleaned = clean(binary)
    straight = deskew(cleaned)
    final = fit_to_mnist(straight)

    stages = {
        "1_gray": gray,
        "2_denoised": denoised,
        "3_ink_dark": ink_dark,
        "4_binary": binary,
        "5_cleaned": cleaned,
        "6_deskewed": straight,
        "7_final": final,
    }
    for name, img in stages.items():
        cv2.imwrite(f"{name}.png", img)
        print(f"wrote {name}.png  {img.shape}")